[package]
name = "osrs-sim"
version = "0.1.0"
authors = ["kyle <kylekroll@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rand = "0.8.0"
structopt = "0.3"
fastrand = "1.4.0"
rayon = "1.5.0"